### ISSUE TITLE
Does not render numbered list after bullet list 

### ISSUE THREAD

**Issue by mdiamond-ns** [enSili-co/markdownplus#2]
v3.2: the following text does not render correctly:
```
* a
* b
* c

1. one
2. two
3. three 
```
The numbers are displayed as bullets, and there is a blank half-line after the first item in the list.
![Screenshot 2024-02-07 at 9 29 08 AM](https://github.com/enSili-co/markdownplus/assets/59977317/888955bf-9539-4f24-96ca-05087801b97b)

**Comment by drkameleon** [comment]
@mdiamond-ns

Apologies for the ultra-delayed response (apparently I missed the notification for this message!)

The issue mentioned above has been fixed:

<img width="817" alt="Screenshot 2024-02-20 at 08 59 57" src="https://github.com/enSili-co/markdownplus/assets/1265028/9539acb0-081a-4dca-8986-57ab7d5779bd">

And the update published as part of v3.3. You may download it from: https://getmarkdown.app/download (although, you'll most likely get an update notification from within the app 😉 )

**Comment by mdiamond-ns** [comment]
Confirmed that 3.3 fixes the issue. Thank you! I will take the liberty of closing the issue.

**Comment by drkameleon** [comment]
> Confirmed that 3.3 fixes the issue. Thank you! I will take the liberty of closing the issue.

Great to hear that!

Don't hesitate to let me know in case you spot any other issue! 😉
